apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-server-pv
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/jacob/git/jacob-hudson.com/infra/config" 